#!/bin/bash
#utility to undress simple covert messages
#in tandum with ./clandest
#KE8CQV

echo "<PROVIDE ENCRYPTED TEXT, MASH THE ENTER KEY, CTRL+D TOEXIT>"

#read message
tr "WpRw3uo&%_V@1>iKF7fN9kq4GaZxI0H#gYDUiJ[8Cc6X^Mj?5+ESPd=;,Qz2r~" "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789" 
